require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'hichaty' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
#  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
#  permissions_path = '../node_modules/react-native-permissions/ios'
#  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'
  pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'
  permissions_path = '../node_modules/react-native-permissions/ios'
   pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
   pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
   pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"

   pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
 
  # pod 'TwilioVideo'



  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  target 'hichatyTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
  use_flipper!({ 'Flipper-Folly' => '2.5.3','Flipper'=>'0.87.0','Flipper-RSocket'=>'1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end
 

target 'hichaty-tvOS' do
  # Pods for hichaty-tvOS

  target 'hichaty-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
